import { Routes } from '@angular/router';

export const spendingRoutes: Routes = [
  { path: '', redirectTo: 'expenses', pathMatch: 'full' },
  { path: 'new', loadComponent: () => import('./pages/expense-form/spending').then(m => m.Spending) },
  { path: 'expenses', loadComponent: () => import('./pages/expenses/expenses').then(m => m.ExpensesDashboard) },
  { path: 'income', loadComponent: () => import('./pages/income/income').then(m => m.IncomePage) },
  { path: 'new-income', loadComponent: () => import('./pages/new-income/new-income').then(m => m.NewIncome) },
  { path: 'new-income/:id', loadComponent: () => import('./pages/new-income/new-income').then(m => m.NewIncome) },
  { path: 'payments', loadComponent: () => import('./pages/payments/payments').then(m => m.Payments) },
  { path: 'payments/:cardId/cycles', loadComponent: () => import('./pages/cycles-history/cycles-history').then(m => m.CyclesHistory) },
  { path: 'new-card', loadComponent: () => import('./pages/new-card/new-card').then(m => m.NewCard) },
  { path: 'people', loadComponent: () => import('./pages/people/people').then(m => m.People) },
  { path: 'new-person', loadComponent: () => import('./pages/new-person/new-person').then(m => m.NewPerson) },
  { path: 'new-person/:id', loadComponent: () => import('./pages/new-person/new-person').then(m => m.NewPerson) },
  { path: 'budget', loadComponent: () => import('./pages/budget/budget').then(m => m.Budget) },
  { path: 'places', loadComponent: () => import('./pages/places/places').then(m => m.Places) },
  { path: 'new-place', loadComponent: () => import('./pages/new-place/new-place').then(m => m.NewPlace) },
  { path: 'new-place/:id', loadComponent: () => import('./pages/new-place/new-place').then(m => m.NewPlace) },
  { path: 'savings', loadComponent: () => import('./pages/savings/savings').then(m => m.Savings) },
  { path: 'new-savings', loadComponent: () => import('./pages/new-savings/new-savings').then(m => m.NewSavings) },
  { path: 'new-savings/:id', loadComponent: () => import('./pages/new-savings/new-savings').then(m => m.NewSavings) },
  { path: 'loans', loadComponent: () => import('./pages/loans/loans').then(m => m.Loans) },
  { path: 'new-loan', loadComponent: () => import('./pages/new-loan/new-loan').then(m => m.NewLoanPage) },
  { path: 'new-loan/:id', loadComponent: () => import('./pages/new-loan/new-loan').then(m => m.NewLoanPage) },
  { path: 'loan-history/:personId', loadComponent: () => import('./pages/loan-history/loan-history').then(m => m.LoanHistoryPage) },
  { path: 'projections', loadComponent: () => import('./pages/projections/projections').then(m => m.Projections) },
  { path: 'pending', loadComponent: () => import('./pages/pending/pending').then(m => m.PendingPage) },
  { path: ':id', loadComponent: () => import('./pages/expense-form/spending').then(m => m.Spending) },
];
